# Generated by Django 3.2 on 2021-11-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='name',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='conf_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
