# Generated by Django 3.2 on 2021-10-04 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('campus', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=250)),
                ('bio', models.TextField()),
                ('display_picture', models.ImageField(default='avatar.png', upload_to='blog/profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=130)),
                ('last_name', models.CharField(max_length=130)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('staud_rating', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('number_of_sales_made', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('display_picture', models.ImageField(default='avatar.png', upload_to='agent/profile/')),
                ('review', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(blank=True, default='None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_agent', to='company.company')),
            ],
        ),
    ]
