# Generated by Django 3.2 on 2021-11-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211025_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='agent',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Estate Agent', 'es'), ('Property Developer', 'pd'), ('Property Owner', 'po')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='conf_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='email_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
