# Generated by Django 3.2 on 2021-11-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_cmsocialmedia'),
        ('accounts', '0003_auto_20211106_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_agent', to='company.company'),
        ),
    ]
