# Generated by Django 3.2 on 2021-11-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='username',
            field=models.CharField(default='None', max_length=130),
        ),
    ]
