# Generated by Django 3.2 on 2021-10-26 16:20

import accommodation.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20211025_1520'),
        ('company', '0003_auto_20211024_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Hostel', 'Hostel')], max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('sex', models.CharField(choices=[('None', 'none'), ('Female', 'Female'), ('Male', 'Male'), ('Unisex', 'Unisex')], default='none', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('room_size', models.CharField(choices=[('One man room', 'One man room'), ('Two man room', 'Two man room'), ('Three man room', 'Three man room'), ('Four man room', 'Four man room'), ('Six man room', 'Six man room'), ('Eight man room', 'Eight man room'), ('Ten man room', 'Ten man room'), ('Miniflat', 'Miniflat'), ('Self contain', 'Self contain')], max_length=25)),
                ('furnished', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('market_status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=15)),
                ('staud_id', models.CharField(max_length=12)),
                ('units_sold', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('number_of_views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('display_picture', models.ImageField(default='accommodation.PNG', upload_to=accommodation.models.get_upload_path_acc)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, unique=True)),
                ('number_of_sales', models.PositiveIntegerField(default=0)),
                ('total_amount_sold', models.PositiveIntegerField(default=0)),
                ('short_description', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_accommodation', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Accommodation Info',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
            ],
            options={
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='TopFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(blank=True, max_length=250, null=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_top_features', to='accommodation.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default='accommodation.png', null=True, upload_to='')),
                ('accomodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodationinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default='accommodation.png', null=True, upload_to=accommodation.models.get_upload_path)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_images', to='accommodation.accommodation')),
            ],
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_info', to='accommodation.accommodationinfo'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.agent'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='accommodation.campus'),
        ),
    ]
