# Generated by Django 3.2 on 2021-10-17 16:04

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='display_picture',
            field=models.ImageField(default='company.jpg', upload_to=company.models.get_upload_path),
        ),
    ]
