# Generated by Django 3.2 on 2021-10-31 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20211024_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(blank=True, max_length=250, null=True)),
                ('social_handle', models.CharField(blank=True, max_length=250, null=True)),
                ('conpany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_socials', to='company.company')),
            ],
        ),
    ]
