# Generated by Django 3.2 on 2021-10-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=13)),
                ('phone_number', models.CharField(blank=True, max_length=256, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(max_length=256)),
                ('accommodation_type', models.CharField(max_length=256)),
                ('campus', models.CharField(max_length=256)),
                ('agent', models.CharField(max_length=256)),
                ('room_size', models.CharField(max_length=256)),
                ('furnished', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=254)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
